export const AppImages = {
    app_logo: require('./app_logo.png'),
    on_boarding1: require('./OnBoarding1.png'),
    on_boarding2: require('./OnBoarding2.png'),
    on_boarding3: require('./OnBoarding3.png'),
    on_boarding4: require('./OnBoarding4.png'),
    banner1: require('./banner1.png'),
    banner2: require('./banner2.png'),
    follower1: require('./follower1.png'),
    follower2: require('./follower2.png'),
    follower3: require('./follower3.png'),
    follower4: require('./follower4.png'),
    follower5: require('./follower5.png'),
    featured1: require('./featured1.png'),
    featured2: require('./featured2.png'),
    nearby: require('./nearby.png'),
    nearby2: require('./nearby2.png'),
    service: require('./services.png'),
    massage: require('./massage.png'),
    map: require('./map.png'),
};